### ISSUE TITLE
csv2regs

### ISSUE THREAD

**Issue by borgmanJeremy** [AvatarBecker/USB2MDIO_PY#1]
Where is the csv2regs dependency located?

**Comment by AvatarBecker** [comment]
I overlooked adding it to the repo, sorry about that. I also added a description for the functionality in the README.md

**Comment by borgmanJeremy** [comment]
Thank you! This saved me the effort of doing exactly this myself!

**Comment by AvatarBecker** [comment]
Glad it helped. :)
